/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type LabeledTree = LabeledNode | LabeledLeaf;
export type LabeledLabelTree = LabeledLabelNode | LabelLabelLeaf;

export interface LabeledNode {
  label: LabeledLabelTree;
  children: LabeledTree[];
}
export interface LabeledLabelNode {
  label: "right" | "left";
  children: LabeledLabelTree[];
}
export interface LabelLabelLeaf {
  label: string;
}
export interface LabeledLeaf {
  label: string;
}
